pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

plugins {
    id 'java'
    id 'com.android.application' version '8.2.0'
}

repositories {
    google()
    mavenCentral()
}

android {
    namespace "com.strangecity"
    compileSdk 34
    
    // Указываем, что всё лежит в одной папке src
    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            assets.srcDirs = ['assets']
        }
    }

    defaultConfig {
        applicationId "com.strangecity"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}

dependencies {
    implementation "com.badlogicgames.gdx:gdx:1.12.1"
    implementation "com.badlogicgames.gdx:gdx-backend-android:1.12.1"
    runtimeOnly "com.badlogicgames.gdx:gdx-platform:1.12.1:natives-armeabi-v7a"
    runtimeOnly "com.badlogicgames.gdx:gdx-platform:1.12.1:natives-arm64-v8a"
}
